### ISSUE TITLE
Smoke Testing of Installation,Ingestion & Input Data,Processing & Output Data,Visualization

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#217]
1. One step cQube_4.0 Installation (Manual Tc's)
- [x] Azure(Devaraja)https://github.com/Sunbird-cQube/community/issues/243
- [x] S3 (Inchara)https://github.com/Sunbird-cQube/community/issues/244
- [x]  On-premise (Chetan)https://github.com/Sunbird-cQube/community/issues/245

2. Checking Ingestion is working or not (Manual Tc's)
- [ ] Azure (Devaraja)https://github.com/Sunbird-cQube/community/issues/246
- [ ] S3 (Inchara)https://github.com/Sunbird-cQube/community/issues/248
- [ ]  On-premise(Chetan)https://github.com/Sunbird-cQube/community/issues/247

3.Checking Data Processing is working or not(Manual Tc's)
- [ ] Azure (Devaraja)https://github.com/Sunbird-cQube/community/issues/249
- [ ] S3 (Inchara)https://github.com/Sunbird-cQube/community/issues/250
- [ ]  On-premise (Chetan)https://github.com/Sunbird-cQube/community/issues/251

4.Checking Output data is generating or not (Manual Tc's) 
- [ ] Azure (Devaraja)https://github.com/Sunbird-cQube/community/issues/252
- [ ] S3 (Inchara)https://github.com/Sunbird-cQube/community/issues/253
- [ ]  On-premise (Chetan)https://github.com/Sunbird-cQube/community/issues/255

5.Checking basic functionalities is working or not for visualization(Manual Tc's)
- [x] Azure (Devaraja)https://github.com/Sunbird-cQube/community/issues/256
- [x] S3 (Inchara)https://github.com/Sunbird-cQube/community/issues/257
- [x]  On-premise(Chetan)https://github.com/Sunbird-cQube/community/issues/258

6.Upgradation From 3.7-to 4.0 (S3)(Manual Tc's) (Manjula)https://github.com/Sunbird-cQube/community/issues/259
- [x] Installation of 3.7
- [x] Upgradation to 4.0
- [ ] Ingestion & Processing of data
- [ ] Visualization

7.Upgradation From 3.7-to 4.0 (On-premise) (Manual Tc's)(Tanushree)https://github.com/Sunbird-cQube/community/issues/260
- [x] Installation of 3.7
- [x] Upgradation to 4.0
- [ ] Ingestion & Processing of data
- [ ] Visualization

**Comment by devu1454** [comment]
Above description is reviewed with Narmatha

**Comment by devu1454** [comment]
1.Completed the smoke testing of azure, s3 and On-premise installation, Found the defects [Defects -List_4.0](https://docs.google.com/spreadsheets/d/1RyXRNQx0O6mlgx8RN6_c1WkJNwxSxra0yzcbg4B23Us/edit#gid=1375251216)
2.Completed the smoke testing of S3 and On-premise upgradation, Found the defects [Defects -List_4.0](https://docs.google.com/spreadsheets/d/1RyXRNQx0O6mlgx8RN6_c1WkJNwxSxra0yzcbg4B23Us/edit#gid=1375251216)

**Comment by devu1454** [comment]
Smoke Testing of Ingestion_api is inprogress due to the blocker of admin_console page

**Comment by RNarmatha** [comment]
The test case documentation is up in the repository.
