### ISSUE TITLE
Testing cQube_4.0

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#220]
- [ ] Smoke Testing of Installation,Ingestion & Input Data,Processing & Output Data,Visualization#217https://github.com/Sunbird-cQube/community/issues/217

- [ ] Functional Testing of Installation,Ingestion & Input Data,Processing & Output Data,Visualization#216https://github.com/Sunbird-cQube/community/issues/216

- [ ] System Testing of Installation,Ingestion & Input Data,Processing & Output Data,Visualization#219https://github.com/Sunbird-cQube/community/issues/219

**Comment by RNarmatha** [comment]
[functional testing ]([Functional Testing of Installation,Ingestion & Input Data,Processing & Output Data,Visualization#216](https://github.com/Sunbird-cQube/community/issues/216))

**Comment by devu1454** [comment]
[Cqube defects list 4.0](https://docs.google.com/spreadsheets/d/1RyXRNQx0O6mlgx8RN6_c1WkJNwxSxra0yzcbg4B23Us/edit#gid=1375251216)

**Comment by RNarmatha** [comment]
The test case documentation are up in Repository
