### ISSUE TITLE
Javascript Basic Concepts Checklist for 16Nov

### ISSUE THREAD

**Issue by FaizanMohammed326** [Sunbird-cQube/community#725]
Concepts to be covered in Javascript:

- Javascript Basics
- Grammar and Tpyes
- Control Flow and Error Handling
- Loops and Iteration.

**Comment by ramyar210** [comment]
- [ ] Javascript Basics
- [ ] Grammar and Types
- [ ] Control Flow and Error Handling
- [ ] Loops and Iteration.

**Comment by murali003** [comment]
- [ ] Javascript Basics
- [ ] Grammar and Tpyes
- [ ] Control Flow and Error Handling
- [ ] Loops and Iteration.

**Comment by RNarmatha** [comment]
Invalid moved to JIRA
