### ISSUE TITLE
1.1 Introduction - NodeJS

### ISSUE THREAD

**Issue by htvenkatesh** [Sunbird-cQube/community#731]
-Please refer the following link

https://drive.google.com/drive/folders/10jSo8RKZ_tp0HoyEQcOxKDJWD5OAZBEK

Topics

- [ ] [What is NodeJs](https://github.com/Sunbird-cQube/community/issues/732)
- [ ] [Installing Node js and creating our first app](https://github.com/Sunbird-cQube/community/issues/733)
- [ ] [Understanding the roles Usage of Node js](https://github.com/Sunbird-cQube/community/issues/734)
- [ ] [Course Outline](https://github.com/Sunbird-cQube/community/issues/735)
- [ ] [How To Get The Most Out Of The Course](https://github.com/Sunbird-cQube/community/issues/736)
- [ ] [Working with the REPL vs Using FIles](https://github.com/Sunbird-cQube/community/issues/737)
- [ ] [Using the Attached Source Code](https://github.com/Sunbird-cQube/community/issues/738)

**Comment by RNarmatha** [comment]
Moved To Jira
